use std::path::{Path, PathBuf};
use std::sync::Arc;
use std::sync::atomic::{AtomicU64, Ordering};
use std::time::Duration;

use anyhow::{Context as _, Result, bail, ensure};
use clap::Parser;
use hd_core::{
    ApiErrorV2, COMPONENT_PROTOCOL_VERSION, DeviceControlCommandV2, DeviceControlRequestV2,
    DeviceControlResponseV2, DeviceControlTokenV2, DeviceSerialEndpointV2,
    FormalComponentConfigurationV2, FormalComponentLaunchV2, FormalComponentReadyV2,
    InstanceActionV2,
};
use hd_device_sim::{
    DeviceCommandV2, DeviceRequestV2, DeviceSimulatorV2, SensorOverrideRuntimeV2, probe,
};
use sha2::{Digest as _, Sha256};
use subtle::ConstantTimeEq as _;
#[cfg(windows)]
use tokio::io::AsyncReadExt as _;
use tokio::io::{AsyncBufReadExt as _, AsyncRead, AsyncWrite, AsyncWriteExt as _, BufReader};
use tokio::sync::{Mutex, watch};
use uuid::Uuid;

const MAX_DEVICE_MESSAGE_BYTES: usize = 64 * 1024;
#[cfg(windows)]
const FIXED_LOCATION_COMMAND: &[u8] = b"CMD_GET_LOCATION";

#[cfg(unix)]
mod location_bridge;
#[cfg(any(unix, windows))]
mod sensor_bridge;

#[derive(Debug, Parser)]
#[command(about = "Signed HD host-side Android device simulator")]
struct Arguments {
    /// Emit the versioned capability document and exit.
    #[arg(long)]
    probe_v2: bool,
    /// Encode the probe as JSON. Required with --probe-v2.
    #[arg(long)]
    json: bool,
    /// Serve newline-delimited legacy V2 requests on stdin/stdout.
    #[arg(long)]
    stdio: bool,
    /// Serve the formal component control contract from a Worker launch document.
    #[arg(long)]
    serve_v2: bool,
    /// Exact owner-only launch document generated by hd-worker.
    #[arg(long)]
    launch: Option<PathBuf>,
}

#[derive(Debug)]
struct FormalContext {
    launch: FormalComponentLaunchV2,
    control_endpoint: String,
    control_token: DeviceControlTokenV2,
    #[cfg_attr(not(windows), allow(dead_code))]
    guest_endpoints: std::collections::BTreeMap<String, DeviceSerialEndpointV2>,
    simulator: Arc<Mutex<DeviceSimulatorV2>>,
    sensor_overrides: SensorOverrideRuntimeV2,
    location_updates: watch::Sender<hd_core::LocationV2>,
    location_delivery_count: AtomicU64,
    location_delivery_evidence: PathBuf,
}

impl FormalContext {
    fn record_location_delivery(&self) -> Result<()> {
        let delivered_sequence = self.location_delivery_count.fetch_add(1, Ordering::SeqCst) + 1;
        let updated_at_unix_millis = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap_or_default()
            .as_millis();
        let evidence = serde_json::json!({
            "schema_version": 1,
            "instance_id": self.launch.instance_id,
            "run_id": self.launch.run_id,
            "delivered_sequence": delivered_sequence,
            "updated_at_unix_millis": updated_at_unix_millis,
        });
        hd_platform::write_owner_only(
            &self.location_delivery_evidence,
            &serde_json::to_vec_pretty(&evidence)?,
        )?;
        Ok(())
    }
}

#[tokio::main]
async fn main() -> Result<()> {
    let arguments = Arguments::parse();
    match (
        arguments.probe_v2,
        arguments.json,
        arguments.stdio,
        arguments.serve_v2,
        arguments.launch.as_deref(),
    ) {
        (true, true, false, false, None) => {
            println!("{}", serde_json::to_string(&probe())?);
            Ok(())
        }
        (false, false, true, false, None) => serve_stdio().await,
        (false, false, false, true, Some(launch)) => serve_formal(launch).await,
        _ => bail!(
            "select exactly one mode: --probe-v2 --json, --stdio, or --serve-v2 --launch <path>"
        ),
    }
}

async fn serve_stdio() -> Result<()> {
    let stdin = tokio::io::stdin();
    let mut lines = BufReader::new(stdin).lines();
    let mut stdout = tokio::io::stdout();
    let mut simulator = DeviceSimulatorV2::default();
    while let Some(line) = lines.next_line().await.context("read device request")? {
        if line.len() > MAX_DEVICE_MESSAGE_BYTES {
            bail!("device request exceeded {MAX_DEVICE_MESSAGE_BYTES} bytes");
        }
        let request: DeviceRequestV2 =
            serde_json::from_str(&line).context("decode device request V2")?;
        let response = simulator.handle(request);
        write_line(&mut stdout, &response).await?;
    }
    Ok(())
}

async fn serve_formal(launch_path: &Path) -> Result<()> {
    let launch_bytes = hd_platform::read_regular_nofollow_limited(launch_path, 64 * 1024)
        .context("read formal component launch")?;
    let launch: FormalComponentLaunchV2 =
        serde_json::from_slice(&launch_bytes).context("decode formal component launch")?;
    ensure!(
        launch.protocol_version == COMPONENT_PROTOCOL_VERSION
            && launch.component == "hd-device-sim",
        "formal launch protocol or component mismatch"
    );
    ensure!(
        launch.component_ready_marker.parent() == launch_path.parent()
            && launch
                .component_ready_marker
                .file_name()
                .and_then(|name| name.to_str())
                == Some("hd-device-sim-ready-v2.json"),
        "formal ready marker is outside the launch directory"
    );
    let (control_endpoint, control_token, guest_endpoints) = match &launch.configuration {
        FormalComponentConfigurationV2::DeviceAdapter {
            control_endpoint,
            control_token,
            guest_endpoints,
            ..
        } => (
            control_endpoint.clone(),
            control_token.clone(),
            guest_endpoints.clone(),
        ),
        _ => bail!("hd-device-sim requires a device_adapter configuration"),
    };
    let simulator = Arc::new(Mutex::new(DeviceSimulatorV2::default()));
    let (location_updates, _) = watch::channel(simulator.lock().await.state().location.clone());
    let sensor_overrides = SensorOverrideRuntimeV2::new(Arc::clone(&simulator));
    let location_delivery_evidence = launch
        .component_ready_marker
        .parent()
        .context("formal component ready marker has no parent")?
        .join("location-delivery-v1.json");
    let context = Arc::new(FormalContext {
        launch,
        control_endpoint,
        control_token,
        guest_endpoints,
        simulator,
        sensor_overrides,
        location_updates,
        location_delivery_count: AtomicU64::new(0),
        location_delivery_evidence,
    });
    let sensor_overrides = context.sensor_overrides.clone();
    tokio::spawn(sensor_overrides.run());
    #[cfg(any(unix, windows))]
    if context.guest_endpoints.contains_key("sensors") {
        let bridge_context = Arc::clone(&context);
        tokio::spawn(async move {
            loop {
                if let Err(error) = sensor_bridge::run(Arc::clone(&bridge_context)).await {
                    tracing::warn!(%error, "sensor Guest bridge disconnected");
                    tokio::time::sleep(Duration::from_millis(100)).await;
                }
            }
        });
    }
    #[cfg(unix)]
    if context.guest_endpoints.contains_key("location") {
        let bridge_context = Arc::clone(&context);
        tokio::spawn(async move {
            loop {
                if let Err(error) = location_bridge::run(Arc::clone(&bridge_context)).await {
                    tracing::warn!(%error, "fixed location Guest bridge disconnected");
                    tokio::time::sleep(Duration::from_millis(100)).await;
                }
            }
        });
    }
    #[cfg(windows)]
    if context.guest_endpoints.contains_key("location") {
        let bridge_context = Arc::clone(&context);
        tokio::spawn(async move {
            loop {
                if let Err(error) = run_fixed_location_bridge(Arc::clone(&bridge_context)).await {
                    tracing::warn!(%error, "fixed location Guest bridge disconnected");
                    tokio::time::sleep(Duration::from_millis(100)).await;
                }
            }
        });
    }
    run_control_server(context, &launch_bytes).await
}

fn publish_ready(context: &FormalContext, launch_bytes: &[u8]) -> Result<()> {
    let ready = FormalComponentReadyV2 {
        protocol_version: COMPONENT_PROTOCOL_VERSION,
        component: context.launch.component.clone(),
        instance_id: context.launch.instance_id,
        run_id: context.launch.run_id,
        launch_sha256: hex::encode(Sha256::digest(launch_bytes)),
        pid: std::process::id(),
        process_start_marker: hd_platform::process_start_marker(std::process::id())?,
    };
    hd_platform::write_owner_only(
        &context.launch.component_ready_marker,
        &serde_json::to_vec_pretty(&ready)?,
    )?;
    Ok(())
}

async fn run_control_server(context: Arc<FormalContext>, launch_bytes: &[u8]) -> Result<()> {
    #[cfg(windows)]
    {
        use tokio::net::windows::named_pipe::ServerOptions;

        let mut first = true;
        loop {
            let mut options = ServerOptions::new();
            options
                .first_pipe_instance(first)
                .reject_remote_clients(true);
            let server =
                hd_platform::create_owner_only_named_pipe(&options, &context.control_endpoint)?;
            if first {
                publish_ready(&context, launch_bytes)?;
            }
            first = false;
            server
                .connect()
                .await
                .context("connect device control pipe")?;
            let connection_context = Arc::clone(&context);
            tokio::spawn(async move {
                if let Err(error) = serve_connection(server, connection_context).await {
                    tracing::warn!(%error, "device component connection failed");
                }
            });
        }
    }
    #[cfg(unix)]
    {
        use std::os::unix::fs::{FileTypeExt as _, PermissionsExt as _};

        let path = PathBuf::from(&context.control_endpoint);
        if let Ok(metadata) = std::fs::symlink_metadata(&path) {
            ensure!(
                metadata.file_type().is_socket(),
                "stale device control endpoint is not a socket"
            );
            std::fs::remove_file(&path)?;
        }
        let listener = tokio::net::UnixListener::bind(&path)?;
        let _guard = SocketGuard(path.clone());
        std::fs::set_permissions(&path, std::fs::Permissions::from_mode(0o600))?;
        publish_ready(&context, launch_bytes)?;
        loop {
            let (stream, _) = listener.accept().await?;
            let connection_context = Arc::clone(&context);
            tokio::spawn(async move {
                if let Err(error) = serve_connection(stream, connection_context).await {
                    tracing::warn!(%error, "device component connection failed");
                }
            });
        }
    }
}

async fn serve_connection<S>(stream: S, context: Arc<FormalContext>) -> Result<()>
where
    S: AsyncRead + AsyncWrite + Unpin,
{
    let (reader, mut writer) = tokio::io::split(stream);
    let mut lines = BufReader::new(reader).lines();
    while let Some(line) = lines.next_line().await.context("read control request")? {
        ensure!(
            line.len() <= MAX_DEVICE_MESSAGE_BYTES,
            "control request exceeded {MAX_DEVICE_MESSAGE_BYTES} bytes"
        );
        let request: DeviceControlRequestV2 =
            serde_json::from_str(&line).context("decode device control request")?;
        let response = handle_control(&context, request).await;
        write_line(&mut writer, &response).await?;
    }
    Ok(())
}

async fn handle_control(
    context: &FormalContext,
    request: DeviceControlRequestV2,
) -> DeviceControlResponseV2 {
    let response = |ok, error| DeviceControlResponseV2 {
        protocol_version: COMPONENT_PROTOCOL_VERSION,
        request_id: request.request_id,
        instance_id: request.instance_id,
        run_id: request.run_id,
        ok,
        error,
    };
    if request.protocol_version != COMPONENT_PROTOCOL_VERSION
        || request.instance_id != context.launch.instance_id
        || request.run_id != context.launch.run_id
    {
        return response(
            false,
            Some(ApiErrorV2::new(
                "device_control_context",
                "device control protocol or run identity mismatch",
            )),
        );
    }
    let supplied = request.bearer_token.as_bytes();
    let expected = context.control_token.as_bytes();
    if supplied.len() != expected.len() || supplied.ct_eq(expected).unwrap_u8() != 1 {
        return response(
            false,
            Some(ApiErrorV2::new(
                "device_control_auth",
                "device control authorization failed",
            )),
        );
    }
    match request.command {
        DeviceControlCommandV2::Ping => response(true, None),
        DeviceControlCommandV2::Action { action } => match apply_action(context, action).await {
            Ok(()) => response(true, None),
            Err(error) => response(
                false,
                Some(ApiErrorV2::new("device_action_failed", error.to_string())),
            ),
        },
    }
}

async fn apply_action(context: &FormalContext, action: InstanceActionV2) -> Result<()> {
    match action {
        InstanceActionV2::SetLocation { location } => {
            apply_simulation(
                context,
                DeviceCommandV2::SetLocation {
                    location: location.clone(),
                },
            )
            .await?;
            context.location_updates.send_replace(location);
            Ok(())
        }
        InstanceActionV2::SetBattery { battery } => {
            apply_simulation(context, DeviceCommandV2::SetBattery { battery }).await
        }
        InstanceActionV2::SetNetworkCondition { condition } => {
            apply_simulation(context, DeviceCommandV2::SetNetworkCondition { condition }).await
        }
        InstanceActionV2::InjectSensor { injection } => context
            .sensor_overrides
            .apply(injection)
            .await
            .map_err(anyhow::Error::from),
        InstanceActionV2::SetSensorPose { pose } => context
            .sensor_overrides
            .apply_pose(pose)
            .await
            .map(|_| ())
            .map_err(anyhow::Error::from),
        _ => bail!("action is not implemented by hd-device-sim"),
    }
}

async fn apply_simulation(context: &FormalContext, command: DeviceCommandV2) -> Result<()> {
    apply_simulation_request(
        context,
        DeviceRequestV2 {
            protocol_version: COMPONENT_PROTOCOL_VERSION,
            request_id: Uuid::new_v4(),
            command,
        },
    )
    .await
}

async fn apply_simulation_request(context: &FormalContext, request: DeviceRequestV2) -> Result<()> {
    let mut simulator = context.simulator.lock().await;
    let mut candidate = simulator.clone();
    let simulation = candidate.handle(request);
    ensure!(
        simulation.ok,
        "{}",
        simulation
            .message
            .unwrap_or_else(|| "device simulation rejected the request".to_owned())
    );
    *simulator = candidate;
    Ok(())
}

#[cfg(windows)]
async fn run_fixed_location_bridge(context: Arc<FormalContext>) -> Result<()> {
    use tokio::net::windows::named_pipe::ClientOptions;

    let endpoint = context
        .guest_endpoints
        .get("location")
        .context("fixed location Guest endpoint is unavailable")?;
    let mut guest_output = open_guest_pipe(|| {
        ClientOptions::new()
            .read(true)
            .write(false)
            .open(&endpoint.guest_output)
    })
    .await?;
    let mut guest_input = open_guest_pipe(|| {
        ClientOptions::new()
            .read(false)
            .write(true)
            .open(&endpoint.guest_input)
    })
    .await?;
    let mut pending = Vec::new();
    let mut chunk = [0_u8; 64];
    let mut location_updates = context.location_updates.subscribe();
    let mut guest_subscribed = false;
    loop {
        tokio::select! {
            changed = location_updates.changed(), if guest_subscribed => {
                changed.context("fixed location update channel closed")?;
                let location = location_updates.borrow().clone();
                write_location(&context, &mut guest_input, &location).await?;
            }
            read_result = guest_output.read(&mut chunk) => {
                let read = read_result?;
                ensure!(read > 0, "fixed location Guest output closed");
                pending.extend_from_slice(&chunk[..read]);
                while let Some(offset) = pending
                    .windows(FIXED_LOCATION_COMMAND.len())
                    .position(|window| window == FIXED_LOCATION_COMMAND)
                {
                    pending.drain(..offset + FIXED_LOCATION_COMMAND.len());
                    guest_subscribed = true;
                    let location = context.simulator.lock().await.state().location.clone();
                    write_location(&context, &mut guest_input, &location).await?;
                }
                if pending.len() > FIXED_LOCATION_COMMAND.len() * 4 {
                    let keep = FIXED_LOCATION_COMMAND.len().saturating_sub(1);
                    pending.drain(..pending.len().saturating_sub(keep));
                }
            }
        }
    }
}

async fn write_location<W>(
    context: &FormalContext,
    guest_input: &mut W,
    location: &hd_core::LocationV2,
) -> Result<()>
where
    W: AsyncWrite + Unpin,
{
    guest_input
        .write_all(format_fixed_location(location).as_bytes())
        .await?;
    guest_input.flush().await?;
    context.record_location_delivery()?;
    Ok(())
}

#[cfg(windows)]
async fn open_guest_pipe<F>(mut open: F) -> Result<tokio::net::windows::named_pipe::NamedPipeClient>
where
    F: FnMut() -> std::io::Result<tokio::net::windows::named_pipe::NamedPipeClient>,
{
    loop {
        match open() {
            Ok(pipe) => return Ok(pipe),
            Err(error)
                if matches!(
                    error.kind(),
                    std::io::ErrorKind::NotFound | std::io::ErrorKind::WouldBlock
                ) || error.raw_os_error() == Some(231) =>
            {
                tokio::time::sleep(Duration::from_millis(50)).await;
            }
            Err(error) => return Err(error.into()),
        }
    }
}

fn format_fixed_location(location: &hd_core::LocationV2) -> String {
    let timestamp_millis = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap_or_default()
        .as_millis();
    format!(
        "Fix,gps,{:.7},{:.7},{:.3},0,{:.3},0,{timestamp_millis},0.1,1,0\n\n\n\n",
        f64::from(location.latitude_e7) / 10_000_000.0,
        f64::from(location.longitude_e7) / 10_000_000.0,
        f64::from(location.altitude_mm) / 1_000.0,
        f64::from(location.accuracy_mm) / 1_000.0,
    )
}

async fn write_line<W, T>(writer: &mut W, value: &T) -> Result<()>
where
    W: AsyncWrite + Unpin,
    T: serde::Serialize,
{
    let mut bytes = serde_json::to_vec(value)?;
    ensure!(
        bytes.len() <= MAX_DEVICE_MESSAGE_BYTES,
        "device response exceeded the limit"
    );
    bytes.push(b'\n');
    writer.write_all(&bytes).await?;
    writer.flush().await?;
    Ok(())
}

#[cfg(unix)]
struct SocketGuard(PathBuf);

#[cfg(unix)]
impl Drop for SocketGuard {
    fn drop(&mut self) {
        let _ = std::fs::remove_file(&self.0);
    }
}
