[package]
name = "hd-rootcanal-adapter"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
hd-core = { path = "../hd-core" }
hd-platform = { path = "../hd-platform" }
hex.workspace = true
rootcanal-rs = { path = "../../../packages/modules/Bluetooth/tools/rootcanal/rust" }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
subtle.workspace = true
tokio.workspace = true
tracing.workspace = true
uuid.workspace = true

[build-dependencies]
cc = "1.2.56"

[lints]
workspace = true
